project:
  type: website
  output-dir: docs
  # resources: 
  #   - "*.mp4"
  #   - "*.mov"

website:
  title: "Invited lectures and workshops"
  # back-to-top-navigation: true
  page-footer: "The material is sourced from **Prof. Kartik Bulusu's** courses taught in GWU unless specified.<br> This is a Quarto website. To learn more about Quarto websites visit <https://quarto.org/docs/websites>.<br> Contact: [Kartik Bulusu](mailto:bulusu@email.gwu.edu)<br> &copy; 2024 All rights reserved"
  page-navigation: true
  bread-crumbs: true
  sidebar:
    style: floating
    # collapse-level: 2
    contents: 
      - href: profile.qmd
        text: Kartik Bulusu's Bio  
      - href: index.qmd
        text: Listing
      # - href: about.qmd
      #   text: About


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 5
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem